name: Infrastructure Mirroring
run-name: ${{ gitea.actor }} - Sincronizando Infraestructura a GitHub

on:
  push:
    branches: [ main ]

jobs:
  sync-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Sync Mirror a GitHub
        if: success()
        run: |
          REMOTE_URL="https://${{ secrets.GIT_HUB_USER }}:${{ secrets.GIT_HUB_SYNC_TOKEN }}@github.com/${{ secrets.GIT_HUB_USER }}/${{ secrets.GIT_HUB_REPO_NAME_INFRA }}.git"
          git push --force "$REMOTE_URL" main:main

      - name: Notificar Éxito a Telegram
        if: success()
        run: |
          MSG=$(git log -1 --pretty=format:"%s")
          TEXT="🏗️ *INFRAESTRUCTURA ACTUALIZADA*%0A%0A"
          TEXT+="📝 *Cambio:* ${MSG}%0A"
          TEXT+="✨ *Mirror:* GitHub Portafolio OK"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d parse_mode="Markdown" \
            -d text="$TEXT"